use_cuda: True
cuda_device_num: 0

physics_engine: 'physx'
compute_device_id: 0
graphics_device_id: 0
num_envs: 32
headless: False

cam_pos: [0., 10., 6.]
cam_target: [0., 2., 0.]

sim_params:
  sim_urdf: 'urdf/cartpole.urdf'
  init_state: [0., 2., 0., -0.707107, 0., 0., 0.707107]
  dt: 0.01
  substeps: 1
  use_gpu_pipeline: True

  physx:
    bounce_threshold_velocity: 0.1
    use_gpu: True
    solver_type: 0
    num_threads: 16
    contact_offset: 0.01
    num_position_iterations: 8
    num_velocity_iterations: 4
    rest_offset: 0.001

  asset_options:
    fix_base_link: True